# All values in no of frames
BACKGROUND_COLOR: gray
FRAME_RATE: 60
FIX_CROSS_TIME: 30 
NO_TRAINING_TRIALS: 2
INTRA_BLOCK_TRAINIG: 2
NO_BLOCKS: 3
TRAINING_CSI: 10
FIX_CROSS_COLOR: black
QUE_COLOR: red
QUE_RADIUS: 20
QUE_SPEED: 2 
QUE_FREQ: 10
QUE_SHIFT: 80
STIM_LETTERS: QCOD
STIM_SIZE: 50
STIM_SHIFT: 800
STIM_TIME: 60
REACTION_TIME: 90
REACTION_KEYS: zxnm
REACTION_KEYS_SEP: 30
# CSI_BAND: [13, 48]
CSI_BAND: [10,12]
STIM_COLOR: black

